server:
  port: 8020
  servlet:
    context-path: /
spring:
  application:   #定义服务名称,如果是多个相同的服务,则名称必须相同
    name: consumer-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: consumer-user-8020
    prefer-ip-address: false               #定义微服务的名称
feign:
  hystrix:
    enabled: true                 #启动熔断器机制 !!!!!!!!!!!!!

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000  #设定断路器超时时间